# Podfile for Lumen QI iOS
platform :ios, '13.0'

# CocoaPods CDN for faster dependency resolution
source 'https://cdn.cocoapods.org/'

use_frameworks!

def capacitor_pods
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../node_modules/@capacitor/camera'
  pod 'CapacitorDevice', :path => '../node_modules/@capacitor/device'
  pod 'CapacitorKeyboard', :path => '../node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../node_modules/@capacitor/local-notifications'
  pod 'CapacitorStatusBar', :path => '../node_modules/@capacitor/status-bar'
  pod 'CapacitorSplashScreen', :path => '../node_modules/@capacitor/splash-screen'
  pod 'CapacitorHaptics', :path => '../node_modules/@capacitor/haptics'
  pod 'CapacitorGeolocation', :path => '../node_modules/@capacitor/geolocation'
  pod 'CapacitorShare', :path => '../node_modules/@capacitor/share'
end

target 'Lumen QI' do
  # Capacitor Pods
  capacitor_pods

  # Additional iOS-specific pods for enhanced functionality
  pod 'Speech'
  pod 'AVFoundation'
  pod 'CoreML'
  pod 'Vision'
  pod 'NaturalLanguage'
  pod 'EventKit'
  pod 'Contacts'
  pod 'UserNotifications'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # iOS deployment target
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      
      # Enable bitcode
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      
      # Build for Apple Silicon and Intel
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end